controller_list:
  - name: sia10f/joint_trajactory_controller
    action_ns: "follow_joint_trajactory"
    type: FollowJointTrajactory
    joints: [joint_s, joint_l, joint_e, joint_u, joint_r, joint_b, joint_t]