joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 10

joint_s_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_s
  pid: {p: 1.0, i: 0.01, d: 1.0}

joint_l_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_l
  pid: {p: 1.0, i: 0.01, d: 1.0}

joint_e_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_e
  pid: {p: 1.0, i: 0.01, d: 1.0}

joint_u_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_u
  pid: {p: 1.0, i: 0.01, d: 1.0}

joint_r_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_r
  pid: {p: 1.0, i: 0.01, d: 1.0}

joint_b_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_b
  pid: {p: 1.0, i: 0.01, d: 1.0}

joint_t_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_t
  pid: {p: 1.0, i: 0.01, d: 1.0}